'use strict';

angular.module('gaheenApp').config(function ($stateProvider) {
	$stateProvider.state('login', {
		url: '/login',
		templateUrl: 'app/account/login/login.html',
		controller: 'LoginCtrl'
	}).state('signup', {
		url: '/signup',
		templateUrl: 'app/account/signup/signup.html',
		controller: 'SignupCtrl'
	}).state('settings', {
		url: '/settings',
		templateUrl: 'app/account/settings/settings.html',
		controller: 'SettingsCtrl',
		authenticate: true
	}).state('verify', {
		url: '/verify',
		templateUrl: 'app/account/verify/verify.html',
		controller: 'VerifyCtrl',
		authenticate: false,
		abstract: true
	}).state('verify.dispensary', {
		url: '',
		templateUrl: 'app/account/verify/verify.dispensary.html',
		controller: 'VerifyDispensaryCtrl',
		authenticate: true
	}).state('verify.manufacturer', {
		url: '',
		templateUrl: 'app/account/verify/verify.manufacturer.html',
		controller: 'VerifyManufacturerCtrl',
		authenticate: true
	}).state('verify.patient', {
		url: '',
		templateUrl: 'app/account/verify/verify.patient.html',
		controller: 'VerifyPatientCtrl',
		authenticate: true
	}).state('verify.physician', {
		url: '',
		templateUrl: 'app/account/verify/verify.physician.html',
		controller: 'VerifyPhysicianCtrl',
		authenticate: true
	}).state('verify.purveyor', {
		url: '',
		templateUrl: 'app/account/verify/verify.purveyor.html',
		controller: 'VerifyPurveyorCtrl',
		authenticate: true
	}).state('verify.transporter', {
		url: '',
		templateUrl: 'app/account/verify/verify.transporter.html',
		controller: 'VerifyTransporterCtrl',
		authenticate: true
	}).state('questionnaire-patient-medications', {
		url: '/questionnaire/patient/medications',
		templateUrl: 'app/account/questionnaire/patient/medications/medications.html',
		controller: 'QuestionnairePatientMedicationsCtrl',
		authenticate: true
	}).state('questionnaire-patient-medicalconditions', {
		url: '/questionnaire/patient/medicalconditions',
		templateUrl: 'app/account/questionnaire/patient/medicalconditions/medicalconditions.html',
		controller: 'QuestionnairePatientMedicalConditionsCtrl',
		authenticate: true
	}).state('questionnaire-patient-strains', {
		url: '/questionnaire/patient/strains',
		templateUrl: 'app/account/questionnaire/patient/strains/strains.html',
		controller: 'QuestionnairePatientStrainsCtrl',
		authenticate: true
	}).state('questionnaire-purveyor-about', {
		url: '/questionnaire/purveyor/about',
		templateUrl: 'app/account/questionnaire/purveyor/about/about.html',
		controller: 'QuestionnairePurveyorAboutCtrl',
		authenticate: true
	}).state('questionnaire-transporter-about', {
		url: '/questionnaire/transporter/about',
		templateUrl: 'app/account/questionnaire/transporter/about/about.html',
		controller: 'QuestionnaireTransporterAboutCtrl',
		authenticate: true
	}).state('questionnaire-transporter-vehicle', {
		url: '/questionnaire/transporter/vehicle',
		templateUrl: 'app/account/questionnaire/transporter/vehicle/vehicle.html',
		controller: 'QuestionnaireTransporterVehicleCtrl',
		authenticate: true
	});
});
