'use strict';

angular.module('gaheenApp').config(function ($stateProvider) {
	$stateProvider.state('login', {
		url: '/login',
		templateUrl: 'app/account/login/login.html',
		controller: 'LoginCtrl'
	}).state('signup', {
		url: '/signup',
		templateUrl: 'app/account/signup/signup.html',
		controller: 'SignupCtrl'
	}).state('settings', {
		url: '/settings',
		templateUrl: 'app/account/settings/settings.html',
		controller: 'SettingsCtrl',
		authenticate: true
	}).state('verify', {
		url: '/verify',
		templateUrl: 'app/account/verify/verify.html',
		controller: 'VerifyCtrl',
		authenticate: false,
		abstract: true
	}).state('verify.dispensary', {
		url: '',
		templateUrl: 'app/account/verify/verify.dispensary.html',
		controller: 'VerifyDispensaryCtrl',
		authenticate: true
	}).state('verify.manufacturer', {
		url: '',
		templateUrl: 'app/account/verify/verify.manufacturer.html',
		controller: 'VerifyManufacturerCtrl',
		authenticate: true
	}).state('verify.patient', {
		url: '',
		templateUrl: 'app/account/verify/verify.patient.html',
		controller: 'VerifyPatientCtrl',
		authenticate: true
	}).state('verify.physician', {
		url: '',
		templateUrl: 'app/account/verify/verify.physician.html',
		controller: 'VerifyPhysicianCtrl',
		authenticate: true
	}).state('verify.purveyor', {
		url: '',
		templateUrl: 'app/account/verify/verify.purveyor.html',
		controller: 'VerifyPurveyorCtrl',
		authenticate: true
	}).state('verify.transporter', {
		url: '',
		templateUrl: 'app/account/verify/verify.transporter.html',
		controller: 'VerifyTransporterCtrl',
		authenticate: true
	}).state('medications', {
		url: '/questionnaire/patient/medications',
		templateUrl: 'app/account/questionnaire/patient/medications/medications.html',
		controller: 'MedicationsCtrl',
		authenticate: true
	}).state('medicalconditions', {
		url: '/questionnaire/patient/medicalconditions',
		templateUrl: 'app/account/questionnaire/patient/medicalconditions/medicalconditions.html',
		controller: 'MedicalConditionsCtrl',
		authenticate: true
	}).state('strains', {
		url: '/questionnaire/patient/strains',
		templateUrl: 'app/account/questionnaire/patient/strains/strains.html',
		controller: 'StrainsCtrl',
		authenticate: true
	}).state('info', {
		url: '/questionnaire/purveyor/info',
		templateUrl: 'app/account/questionnaire/purveyor/info/info.html',
		controller: 'InfoCtrl',
		authenticate: true
	});
});
